### PR TITLE
Updated package's subfolder

### PR DESCRIPTION
**Pull request by fmauch**
For the 1.0.3 release moveit changed their package structure.

### CODE REVIEW

**Review by acxz — CHANGES_REQUESTED** [review]
Sweet thx for the PRs! However, for the packages to be synced and updated on the AUR. The pkgrel has to be updated as well as the .SRCINFO.
See: https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel
and https://wiki.archlinux.org/index.php/.SRCINFO

**Comment by fmauch** [comment]
sure!

**Comment by fmauch** [comment]
Note, that this depends on https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/21

**Comment by fmauch** [comment]
Closing in favor of #3

**Pull request closed without merging**
